### ISSUE TITLE
Sync failed, please check network

### ISSUE THREAD

**Issue by robkay01** [nervosnetwork/neuron#1652]
**Describe the bug**
Neuron Wallet Sync Failed

**Environment (please complete the following information):**
 - OS & Version: Windows 10
 - Neuron Version [e.g. 0.28.0] 0.30.0 but was having the same issue with previous version before upgrading
 - Block Number: Sync failed, cannot check

I have cleared the cache and restarted several times and it doesn't change it. When you first open Neuron it trys to connect but then gives the sync failed message after about 10 seconds. My internet connection is fine.
[neuron_debug_1589717671295.zip](https://github.com/nervosnetwork/neuron/files/4640211/neuron_debug_1589717671295.zip)

**Steps To Reproduce**

**Screenshots**

**Comment by Keith-CY** [comment]
The `status.json` from the debug info indicates that the CKB Node doesn't work properly.

Usually, it's broken due to the malformed peer store files and can be fixed by deleting files in `%APPDATA%\Neuron\chains\mainnet\data\network\peer_store`.

Please check if the CKB Node Log(`%APPDATA%\Neuron\chains\mainnet\data\logs`) includes error messages like `main ERROR panic  thread 'main' panicked at 'Init network state failed: PeerStore(Serde(Error("expected value", line: 1, column: 1)))': `.

If it does, please try the solution mentioned above, otherwise please provide the latest error messages from the CKB Node Log. Thanks.

**Comment by zengbing15** [comment]
The bug is triggered by peer_store library issue on windows system, now is resolved by deleting the data files in `%APPDATA%\Neuron\chains\mainnet\data\network\peer_store`. Close this issue.

**Comment by flatratetech** [comment]
how do I delete these data files I believe I have the same issue
