### ISSUE TITLE
No need to synchronize from the genesis block

### ISSUE THREAD

**Issue by huazhouwang** [nervosnetwork/neuron#1809]
If i create an absolute new wallet, why should i synchronize from the genesis block? Or may be i can set a starting sync block?

**Comment by katat** [comment]
Hi @huazhouwang 

Could you please let us know which version you are currently using?

In the earlier versions than 0.32, it will indeed do the re-sync after created a new wallet. However, this has been improved in the latest versions.

With the versions 0.32 forward, it shouldn't need to synchronize from the genesis block after created a new wallet.

**Comment by huazhouwang** [comment]
yes, I just upgraded to the latest version 0.32

**Comment by huazhouwang** [comment]
I installed the latest version of the neuron (which is 0.32.1), then created a new wallet, and found that it needs to be synchronized from the genesis block

**Comment by katat** [comment]
Then this behavior is unexpected. It shouldn't need to do the re-sync in this scenario. Could you please export the debug logs and share it with us for further investigations? Thank you.

![Screen Shot 2020-08-10 at 5 58 03 PM](https://user-images.githubusercontent.com/1587352/89771644-3d828380-db33-11ea-8e5b-acf455b5a449.png)

**Comment by huazhouwang** [comment]
here
[neuron_debug_1597054653634.zip](https://github.com/nervosnetwork/neuron/files/5050241/neuron_debug_1597054653634.zip)

**Comment by katat** [comment]
Thanks @huazhouwang 

From what I saw in the log, it is still in the progress of indexing. If you upgraded from the earlier version than 0.32, then it will do the re-sync based because the new version adopt a new indexing mechanism. This re-sync after upgraded from the earlier major versions is expected.

Therefore, I would suggest waiting for the current synchronization to finish before having another try to see if creating a new wallet indeed triggers a re-sync.

_Tip: Please connect to the local bundle node if you want to get the synchronization finished much faster. Connecting to a remote node could lead to a very slow synchronization because of the network latency or other effects introduced by the network environments._

**Comment by huazhouwang** [comment]
thx. I suggest that it is possible to add an option for users to choose whether to start synchronization from the genesis block? Or allow user to set up the initial block？
