### ISSUE TITLE
CKB Deposit not arrived to my Neuron Wallet last 3 days.

### ISSUE THREAD

**Issue by MizanSK** [nervosnetwork/neuron#1883]
I've send 19963.99 CKB from the Exchange account to my Neuron Wallet address on 9th October 2020. Its 11 October and my Wallet Balance is not updated and still showing 0 Balance. Please help me to resolve the issue.
Seed Phrase: ckb1qyq80svexx6z3wpnlyhy9jcycdpr060744vqmtkne0

**Comment by katat** [comment]
Hi @MizanSK 

Please try the following instructions to resolve the issue:
1. Make sure you have the latest version(0.32.3) of Neuron, and it is fully synced.
2. Clear cache. _Settings => General => Clear cache => Refresh_
3. If step 2 doesn't work, try to rebuild index data. This might take quite a while to complete, but generally can be finished within an hour. _Settings => General => Clear cache => Fully rebuild index_

Let us know if the issue is still not resolved after following the steps above.

**Comment by MizanSK** [comment]
Software updated and the version is 33.0, not 32.3.
I've completed Step 2 and 3. 
But there is no improvement and still same as earlier.
Balance is still 0
<img width="897" alt="1" src="https://user-images.githubusercontent.com/72675649/95668729-71693c00-0baa-11eb-87c1-225a58ebdc3c.PNG">
<img width="645" alt="2" src="https://user-images.githubusercontent.com/72675649/95668731-729a6900-0baa-11eb-9954-ef1d229f8e2e.PNG">

**Comment by katat** [comment]
From the screenshot, the synchronization seems to be still in progress. Please wait for completing the synchromization. Depends on the performance of your computer, it generally can complete the sync in an hour.

**Comment by MizanSK** [comment]
After Transfer the CKB from the exchange, The PC is running last 3 days as Synchronization in Progress.
Now After Clearing the Cache, How many days will it take?
My other Crypto Wallets (ADA Daedalus, Matic Wallet and VchainThor wallet) ar completing Synchronization in few munities. I really don't Understand, why The Neuron performance is like this?

**Comment by MizanSK** [comment]
Would you please check the Nervous Scan and Update?

**Comment by katat** [comment]
It shouldn't take such a long time finish the sync. Normally it should be finished within an hour. 

Please export the debug log(under the help menu) and send it to us for diagnosing the sync issue.

**Comment by MizanSK** [comment]
[neuron_debug_1602384891164.zip](https://github.com/nervosnetwork/neuron/files/5360518/neuron_debug_1602384891164.zip)

**Comment by MizanSK** [comment]
Ok. Finally Updated my Wallet. 
Have you find the Problem?
may I proceed to Transfer my remain CKB to Transfer safely? or it will be another long process again?

**Comment by katat** [comment]
Thanks for the debug logs attached. We will take a look. 

Meanwhile, does your last reply mean your neuron client is fully synced and balance got updated?

Normally if the Neuron app stays in sync, the transfer only needs to wait for the confirmation on the chain, which should only takes a few minutes at maximum. It shouldn't need to wait for such a long time(it is abnormal, could be due to network environment or something else, we will take a look at the log you provided) you experienced for the initial sync.

**Comment by MizanSK** [comment]
Yes. Neuron Clint is synchronized completely.
But feeling a bit reluctant to transfer another 200K CKB, 
Either it transferred Smoothly?
