### ISSUE TITLE
Neuron Wallet Not Syncing With Mainnet

### ISSUE THREAD

**Issue by CryptoGitmo** [nervosnetwork/neuron#1898]
Running Neuron 0.33.0, CKB Client v0.35.1, on Windows 10.  Neuron is not syncing with Mainnet.  Cleared cache.  No change. 
Block number synced = 0.  Any suggestions?  Attached is debug file.  Thank you for any help.

[neuron_debug_1604910710815.zip](https://github.com/nervosnetwork/neuron/files/5509105/neuron_debug_1604910710815.zip)

**Comment by katat** [comment]
Hi @CryptoGitmo 

I also saw your message in the NervosNetwork channel.

To help figure out the cause of this issue, could you please run the ckb.exe under the folder C:\Users\[your user name]\AppData\Local\Programs\Neuron\bin

And see if it throws any errors from the ckb node.

Or if you can execute it through the command line, please try this command: `C:\Users\[your user name]\AppData\Local\Programs\Neuron\bin\ckb run -C C:\Users\[your user name]\AppData\Roaming\Neuron\chains\mainnet\`

Normally this command should start up a ckb node. Otherwise, we will need to figure out why the ckb node can’t be booted up on your computer, leading to the situation where your Neuron can’t connect to the mainnet.

**Comment by katat** [comment]
Also, could you please share your hardware setup, such as the CPU? This would be also valuable for us to debug.

**Comment by farmerxt** [comment]
i add my comment 
after updating to newest version
failed sync
clear cache not working - run as administrator not working


[2020-01-19 20:30:08.833] [error] Fail to connect to the network. Is CKB node running?
[2020-01-19 20:30:09.609] [error] Get cached meta info failed: Error: File meta-info.json not found
[2020-05-14 17:26:04.404] [error] Database:	fail to open leveldb datastore: undefined
[2020-05-14 17:26:06.688] [error] Network:	fail to connect to the network. Is CKB node running?
[2020-05-14 17:26:07.210] [info] Network:	switched to: {
  id: 'mainnet',
  name: 'Mainnet',
  remote: 'http://localhost:8114',

deinstalled reinstalled ( all user ) 
imported seed 
still no SYNC win10 64bit  034 rc1

**Comment by katat** [comment]
Hi @farmerxt 
Looks like you are using an old version of Neuron.
Please try installing the version 0.33.1

**Comment by farmerxt** [comment]
newest version ! deinstalled old

**Comment by katat** [comment]
Which version are you using at the moment?
Also try installing the vcredist x64 https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by farmerxt** [comment]
i installed visual c 
using neuron 0.34
client 0.35

MAINNET connecting..... but no connection !

**Comment by katat** [comment]
Got it. Could you please export the debug log and share it here. We will investigate from there.

**Comment by katat** [comment]
Make sure you installed the x64 version of vcredist, not the x86 version.

**Comment by farmerxt** [comment]
[neuron_debug_1606216080844.zip](https://github.com/nervosnetwork/neuron/files/5589422/neuron_debug_1606216080844.zip)

**Comment by katat** [comment]
Based on the log, looks like the CKB node is migrating data from the older version. It might take a while, but normally wouldn't need to take more than an hour. Please keep Neuron running while it displays "connecting".

**Comment by farmerxt** [comment]
ok will do ... says blocks synced 0 % although ... will update you

**Comment by farmerxt** [comment]
indeeed ! after long time of wait it starts syncing !
thanks for support
