### ISSUE TITLE
0.36.0-alpha.1 - User reported that when trying to send to short address with Ledger, long address was shown on device and a timelock was required

### ISSUE THREAD

**Issue by matt-quinn** [nervosnetwork/neuron#2011]
**Describe the bug**
(Using Ledger with Neuron) 

User reported that they provided a short address to send to, the Ledger device showed a long address and they were required to enter a timelock in order to complete the transaction

**Environment (please complete the following information):**
 - OS & Version: OSX
 - Neuron Version 0.36.0-alpha.1
 - Block Number: Unknown (recent transaction)

**Steps to reproduce:**
1. Send
2. Enter short address in address dialog
3. Enter amount
4. Sign with Ledger - long address is shown on Ledger , time lock is required to complete transaction in Send dialog

**Comment by yuche** [comment]
The address issue is because the Ledger device does not yet support short address translation, a future upgrade of the [ledger app](https://github.com/obsidiansystems/ledger-app-nervos) may solve this problem.

Time lock is a user-set configuration that you can set to auto-lock according to [Ledger documentation](https://support.ledger.com/hc/en-us/articles/360017152034-Set-auto-lock).

**Comment by Keith-CY** [comment]
Stale issue
