### ISSUE TITLE
wallet will not sync on windows Edition	Windows 10 Home Version	20H2 Installed on	‎6/‎14/‎2021 OS build	19042.1083 Experience

### ISSUE THREAD

**Issue by DawnChar12** [nervosnetwork/neuron#2046]
**Describe the bug**
Please enter details.

**Environment (please complete the following information):**
 - OS & Version: [e.g. Windows 10, macOS 10.15.2, Linux Ubuntu 18.04]
 - Neuron Version [e.g. 0.28.0]
 - Block Number: [Check that from `Overview` - `Blockchain Status` for v0.29.0-rc2 or before, or hover onto the left bottom syncing status area for v0.29.0 and later]

**Steps To Reproduce**

**Screenshots**

**Comment by DawnChar12** [comment]
64-bit operating system, x64-based processor 
AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G   2.70 GHz
Neuron 0.35.0

OVERVIEW
BALANCE :  0 CKB

Recent Activities
no recent activities

**Comment by kellyshang** [comment]
Hi @DawnChar12 , sorry for the late reply. Could you have a try to upgrade the Neuron to the latest version of [v0.100.0](https://github.com/nervosnetwork/neuron/releases/tag/v0.100.0) and see if it works? (PS. this version will delete the whole bundled ckb node data/indexer data to re-sync, because the bundled ckb has been upgraded)

**Comment by kellyshang** [comment]
Will close this issue since there is no news. You can re-open this issue if there is any problem.
