### ISSUE TITLE
CKB sent from Binance to neuron didn't arrive in days.

### ISSUE THREAD

**Issue by Anubix8** [nervosnetwork/neuron#2157]
I was sending CKB from Binance to neuron a few days ago and it still didn't arrive,
I checked at the explorer and the CKB was there but still wasn't in the neuron wallet.
Wallet is synced, clearing cache didn't help, and updating to newest version also didn't help.
Don't know what to do,I hope someone can help.
Thanks.

[neuron_debug_1635843081752.zip](https://github.com/nervosnetwork/neuron/files/7466853/neuron_debug_1635843081752.zip)

**Comment by kellyshang** [comment]
@Anubix8 Does the address existed in the Neuron adderss book list? ( from `Receive` page - click the `Adress Book` button)

**Comment by Anubix8** [comment]
No it doesn't but i can see it in the history of transactions

**Comment by Anubix8** [comment]
here we sent 30000 CKB from Binance to neuron and it arrived but now I sent 50000 CKB and it never arrived to neuron

**Comment by Anubix8** [comment]
![Snimka zaslona 2021-11-09 191250](https://user-images.githubusercontent.com/71311961/140980820-28cbcff9-bce7-45e9-87ea-88b86263df02.png)

**Comment by Anubix8** [comment]
here we were sending some CKB from Binance to neuron and it arrived but now I sent 50000 CKB and it never arrived to neuron

**Comment by kellyshang** [comment]
> No it doesn't but i can see it in the history of transactions

Since the address doesn't list in your Wallet address book, then it's not the correct wallet you were chosen. 
Please check where the address you copied from, make sure the wallet displayed in the Neuron is the correct one.

**Comment by Anubix8** [comment]
> > No it doesn't but i can see it in the history of transactions
> 
> Since the address doesn't list in your Wallet address book, then it's not the correct wallet you were chosen. Please check where the address you copied from, make sure the wallet displayed in the Neuron is the correct one.

But this wasn't the first time sending CKB to that address, that was my address, but it suddenly disappeared from my wallet.

**Comment by kellyshang** [comment]
>But this wasn't the first time sending CKB to that address, that was my address, but it suddenly disappeared from my address book.

@Anubix8 Could you try to switch to other wallet in Neuron to see if the address appears in other wallet's "Address Book"?

Switch wallet:
![image](https://user-images.githubusercontent.com/28836185/143222051-78770df3-1b92-40e2-9dec-9590e28cca2c.png)
Goto "Address Book" and check from the address list:
![image](https://user-images.githubusercontent.com/28836185/143222103-a52483e7-85b7-4d82-af10-315f1fd1a98e.png)

**Comment by Anubix8** [comment]
> > But this wasn't the first time sending CKB to that address, that was my address, but it suddenly disappeared from my address book.
> 
> @Anubix8 Could you try to switch to other wallet in Neuron to see if the address appears in other wallet's "Address Book"?
> 
> Switch wallet: ![image](https://user-images.githubusercontent.com/28836185/143222051-78770df3-1b92-40e2-9dec-9590e28cca2c.png) Goto "Address Book" and check from the address list: ![image](https://user-images.githubusercontent.com/28836185/143222103-a52483e7-85b7-4d82-af10-315f1fd1a98e.png)

I have only one wallet

**Comment by Anubix8** [comment]
I have only one wallet

**Comment by kellyshang** [comment]
@Anubix8 Are you the same person with @ttot1977 ?
Seems you have posted the same issue with https://github.com/nervosnetwork/neuron/issues/2036 , if you are the same person, please do not report duplicate issues.

**Comment by kellyshang** [comment]
> here we were sending some CKB from Binance to neuron and it arrived but now I sent 50000 CKB and it never arrived to neuron

From this sentence and the screenshot you sent before, the address of "ckb1qyqxngcpv884mq3g4tqqc09jku4g2lkwlnmqhzlrdw" is the sender in Binance and you have sent to the receiver of "...lhxp" which was in your Neuron wallet. So seems you sent the 50000 CKB back to the sender in Binance.
You'd better check the address and the balance in Binance.

**Comment by ttot1977** [comment]
Thank you for help I have wroten to Binance support and now waiting for
their answer

čet, 25. stu 2021. 04:30 kellyshang ***@***.***> je napisao:

**Comment by ttot1977** [comment]
Anubix8 is my son and it is about the same problem.

čet, 25. stu 2021. 04:20 kellyshang ***@***.***> je napisao:

**Comment by kellyshang** [comment]
in order to do not disturb other person, let me reply [your comments](https://github.com/nervosnetwork/neuron/issues/2036#issuecomment-980357603) in this opened issue:

Can you try to recall for me for below questions:
Firstly let's see the transaction history of the address: https://explorer.nervos.org/address/ckb1qyqxngcpv884mq3g4tqqc09jku4g2lkwlnmqhzlrdw
![image](https://user-images.githubusercontent.com/28836185/143666800-a6bf9180-92e8-4b0e-a7c5-f9d369b9667e.png)

Q1: the transaction happend on (Block 4,683,089) 2021/07/01 I belive it should be your withdrawal from Binance to your Neuron wallet `A`, right? 
Q2: then as to the transaction which happened on (Block 4,739,364) 2021/07/07, can I ask why you transfer the CKB to the other wallet `B`( which is your current wallet that you exported the debug info from)? What happened after this transaction? Is there any possible that you deleted the wallet `A`? Can you try to find out the mnemonic keyword (that you created the wallet `A`) from somewhere? Then re-import the mnemonic keyword of the wallet `A` to Neuron.

**Comment by ttot1977** [comment]
Hello Kellyshang

thank you for quick reply.

Q1: Yes it was transaction withdrawal from Binance to Neuron wallet,
screenshot is down in mail
Q2: Im not shure what happened on 07.07.2021. on block 4.739.364 it was
transaction -30.034,1137 CKB which we put on staking process in Neuron
Nervos DAO.  I dont even know that I have wallet A and wallet B? I just
have one wallet see screenshot down. So I definitely have not deleted
another wallet?! But if we remember first problem from July it was problem
that we have a same wallet on one old lap top which we havent synced few
months? Maybe there is a problem? I will try to sync that old laptop now
and then see if CKB's will come in to wallet?

So we have create just ONE wallet and we have ONE mnemonic keyword and I
want to delete Neuron app from that old lap top are you suggesting that I
try to reimport mnemonic keyword and wallet to Neuron on my new lap top? I
will message you with info after old lap top sync do 100%

[image: image.png]

[image: image.png]

[image: image.png]

sub, 27. stu 2021. u 04:51 kellyshang ***@***.***> napisao je:

**Comment by kellyshang** [comment]
@ttot1977 Your screenshots failed to display again. I have remind you several times that please don't reply by the email.

On the old lap top you can firstly check if the address `...lrdw` listed in the Neuron wallet A's `Address Book` (left menu `Receive` - click button `Address Book` ).
If it's the right wallet, you can reimport the mnemonic keyword to Neuron on your new lap top.

**Comment by ttot1977** [comment]
Hello Kellyshang

after many days old lap top finally fully synced and JEP there is now my
"losted" CKB's so we have found them (HAPPY)
address ...lrdw is listed in receive menu, I have successfully transfer my
CKB's now back to Binance.

But I have more CKB's on staking in Neuron wallet and question is when I
will make unstake back to wallet now I'm afraid that they will also
transfer back to that wallet which is on my old lap top?
And I do not understand how is it possible to have wallet A and wallet B
when I installed same application and SAME wallet sith same mnemonic
keywords on both lap tops?
How to deinstall that old wallet on old lap top and be shure that every
further transaction or UNSTAKING from Neuron wallet will NOT send CKB's
again in this wallet because this old lap top is so slow and Im not
shure it will work long any more...
So how is Neuron wallet working on more lap tops with same wallet and same
mnemonic keyword? how to safely unistal Neuron wallet from old lap and not
lose ckb's anymore?
thank you

ned, 28. stu 2021. u 05:13 kellyshang ***@***.***> napisao je:

**Comment by kellyshang** [comment]
You can export the keystore from the old lap top and import it to the new lap top with same password.

Export keystore from old lap top:
![image](https://user-images.githubusercontent.com/28836185/145604658-e7b84844-5b9b-4772-8042-b682188c2eac.png)
Import keystore to the new lap top:
![image](https://user-images.githubusercontent.com/28836185/145604604-3cfb877b-d084-4868-b4c4-fb9f55dbb6e1.png)
