### ISSUE TITLE
Upated Wallet

### ISSUE THREAD

**Issue by tgormglitch** [nervosnetwork/neuron#2235]
After the update I received the message stating I require x64 version of MVC++. In the previous version I also got this message however, I was able to skip it and the wallet would be functional. There is now no skip button and when I hit Install and Exit, it closes the wallet and sends me to Microsoft's Official page and closes the wallet. I have downloaded the most recent version and restarted, upon opening the same thing happens. The wallet buttons are functional even while this message is displayed but it no longer attempts to sync.
![neuron](https://user-images.githubusercontent.com/74471741/149520684-aa144567-90d9-488b-b1fa-b4382723df23.JPG)
[neuron_debug_1642177122011.zip](https://github.com/nervosnetwork/neuron/files/7871715/neuron_debug_1642177122011.zip)

**Comment by kellyshang** [comment]
Hi @tgormglitch , actually this behavior is really strange so that I'm not quite sure the reason.

According to your debug info, your local ckb node and Neuron can sync normally before, in theory the vc redist should have been installed on your machine thus the warning window should not be shown up when start the Neuron.

Could you help do some works to help us locate the problem more accurately:
1. Open the Powershell on your PC, type this command and see what returned: `REG QUERY HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64`
2. Can you please help take a screenshot of your installed app as below especially including the vc redist related:
![image](https://user-images.githubusercontent.com/28836185/150512965-9749e09b-1cdc-4519-b70c-7cf9940a2bde.png)
3. Could you tell us which location were you chose when installing the Neuron - ( `for all users` or `just me` ) ?

**Comment by tgormglitch** [comment]
Thanks for responding Kelly. Here are the screenshots you requested and I installed it for **just me**.
![vc1](https://user-images.githubusercontent.com/74471741/150538914-e63f526a-8af2-4034-896e-dede808e9329.JPG)
![vc2](https://user-images.githubusercontent.com/74471741/150538918-b696ae1a-598b-4247-a875-51e4a1dc8e90.JPG)
![vc3](https://user-images.githubusercontent.com/74471741/150538921-ab12a5f0-5e06-44b4-9b5e-bf1e8f6c35f4.JPG)

**Comment by yanguoyu** [comment]
Hi, @tgormglitch, can you download [latest version 0.101.3](https://github.com/nervosnetwork/neuron/releases/tag/v0.101.3) and try again.In the release we added some logs to find why this happened.Can you help send new logs?
