### ISSUE TITLE
Suggestion: Wallet Storage Location

### ISSUE THREAD

**Issue by dapptain** [nervosnetwork/neuron#2249]
This is not a bug, but a feature request rather.

 It would be great if we could specify the folder/location on our local HDD for where to store the chain's data.

**Comment by ancoron** [comment]
Worked around it by relocating `~/.config/Neuron` and creating a symbolic link in place of the directory.

**Comment by Vtarj** [comment]
> Worked around it by relocating and creating a symbolic link in place of the directory.`~/.config/Neuron`

How do you get people who don't know technology to do it

**Comment by Keith-CY** [comment]
Thanks for the workaround @ancoron 

Hi @dapptain and @Vtarj , it seems to be more desired to specify the path of chain's data with CKB node growing dramatically. We'll list it in our features and enable it within one or two months. I'll update this issue once it's done.

**Comment by Keith-CY** [comment]
Hi @dapptain @ancoron @0xfather 

We just released Neuron v0.103.2 https://github.com/nervosnetwork/neuron/releases/tag/v0.103.2 which supports `custom data path` by PR https://github.com/nervosnetwork/neuron/pull/2433, now data paths of ckb node and ckb indexer can be set in `Setting -> Data`

Remember to move current data into the new directory so neuron can continue from a synchronized height. 

Current file directory can be opened by clicking `open directory` next to the displayed path
![Preference copy](https://user-images.githubusercontent.com/7271329/178102806-00b0a1f8-dc10-4a51-aeb3-d54df8418371.jpg)

**Comment by spg1383** [comment]
Hi, I've tried to change both paths but it seems it does not work, trying to connect in infinite loop :
![image](https://user-images.githubusercontent.com/119402861/204476009-09a51b5b-9034-46d8-bf3a-e47c06934da0.png)

**Comment by Keith-CY** [comment]
> Hi, I've tried to change both paths but it seems it does not work, trying to connect in infinite loop : ![image](https://user-images.githubusercontent.com/119402861/204476009-09a51b5b-9034-46d8-bf3a-e47c06934da0.png)

Hi @spg1383 sorry for that, but I'd suggest holding this feature on until the next version of Neuron(which should be released soon after ckb@v0.106.0 is released) because `ckb-indexer` has been merged into `ckb node` so the storage directory will be updated, too. Only one path should be specified.

Besides, there will be a data migration to merge data of ckb-indexer into ckb-node so the data can be moved easily.

Ref: 
- merge indexer: https://github.com/nervosnetwork/ckb/pull/3609
- update of neuron: https://github.com/Magickbase/neuron-public-issues/issues/71
- release ckb@v0.106.0: https://github.com/nervosnetwork/ckb/issues/3710
