### ISSUE TITLE
Export Dates Incorrect

### ISSUE THREAD

**Issue by DrakeBliss** [nervosnetwork/neuron#2312]
When I export from the Nueron Wallet, the dats on some transactions is NOT the SAME??

Wallet Show 11/25 Export Shows 11/26

Also the export date has more than YYYY-MM-DD HH:MM:SS

For example 2021-11-26 04:01:30.340

What is the .340 above mean???

See Images below.
![Snap1](https://user-images.githubusercontent.com/80055098/159990427-bd4332e7-729f-461d-b5d6-de4470c9b0fa.jpg)
![Snap2](https://user-images.githubusercontent.com/80055098/159990430-68a8da19-432f-40af-aa16-f5be87bfc65d.jpg)

**Comment by Keith-CY** [comment]
Hi @DrakeBliss 
The displaying time is using a local time format so that it can be recognized easily
While the time in exported records is in UTC time format, which is more general in data operation since it excludes the effect of time zone.

If I were right, you should be in UTC-5 Timezone according to the screenshot, so the UTC time is `2021-11-26 04:01:30` while your local time is UTC time -5h, namely `2021-11-25 23:01:30`

Here's an online converter so you can verify it https://www.timeanddate.com/worldclock/converter.html?iso=20211126T040100&p1=3919

BTW, the `.340` is millisecond, it equals 0.34s
