### ISSUE TITLE
Unable to update neuron wallet

### ISSUE THREAD

**Issue by aaomotayo** [nervosnetwork/neuron#2314]
**Describe the bug** (Please enter details, the more detail the better)

While attempting to install the new version for my wallet, I'm getting Error: Code signature at URL file:///Users/gutzy/Library/Caches/com.nervos.neuron.ShipIt/update.Tlcnz57/Neuron.app/ did not pass validation: code failed to satisfy specified code requirement(s). I've got a macOS. Can you help please? Guess I'm missing some files or they do not match.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
> **Describe the bug** (Please enter details, the more detail the better)
> 
> While attempting to install the new version for my wallet, I'm getting Error: Code signature at URL file:///Users/gutzy/Library/Caches/com.nervos.neuron.ShipIt/update.Tlcnz57/Neuron.app/ did not pass validation: code failed to satisfy specified code requirement(s). I've got a macOS. Can you help please? Guess I'm missing some files or they do not match.
> 
> **Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
> 
> **Screenshots** (If applicable, add screenshots to help explain your problem.)

Hi @aaomotayo , don't worry about this warning.

LR; DR, this was annotated in the release note and you can download Neuron from the release page to adopt a new developer Id certificate.

It was caused by the migration of our developer Id certificate in Apple.

Because we, developers of Neuron, are now running our own group and will focus on neuron (won't participate in other toolchain development in Cryptape), we apply a new developer id certificate(distributed by Nervina Labs) and replace the old one(distributed by Cryptape).

The certificate verification will fail when upgrading from the one signed by the old certificate, but you can download Neuron from the release page to adopt the new certificate, it should pass through the GateKeeper of macOS.
