### ISSUE TITLE
Transaction pending as of 3-18

### ISSUE THREAD

**Issue by ITFixEZ** [nervosnetwork/neuron#2334]
**Describe the bug** (Please enter details, the more detail the better)
I was transfering from DAO back to main wallet, collecting my rewards in other wards. I began staking 10-26-2021, attempted withdraw 3-18 , Blocked synched 100%, transaction: 0x879f94d191cd73ab5bcba6846023c92ec1c66ec83c69228935bc33055395ac88
still pending 

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

[neuron_debug_1650136663712.zip](https://github.com/nervosnetwork/neuron/files/8500510/neuron_debug_1650136663712.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

![Screen Shot 04-16-22](https://user-images.githubusercontent.com/46285015/163688724-69899f65-d6f2-45a1-b908-85aa2bdf032c.PNG)

**Comment by Keith-CY** [comment]
Hi, @ITFixEZ 

The transaction `0x879f94d191cd73ab5bcba6846023c92ec1c66ec83c69228935bc33055395ac88` is absolutely not committed on chain. Since it's been a month, I think it's a bug of neuron's cache mechanism. This case happens, and usually can be resolved by `clear cache` in the setting window.

Have you ever tried `clear cache`? It won't take long.

And according to the logs, the last messages are all

```
Insufficient available balance, please try again when last transaction has been confirmed. Error: Insufficient available balance, please try again when last transaction has been confirmed.
```

This happens with cache problems too.

**Comment by ITFixEZ** [comment]
I will try this as I wanted to check with support before moving forward with a re-synch, I will move forward with this now and update asap. I have also provided "basic info" sShot for the records. TY for timely response !!
![basicIssue](https://user-images.githubusercontent.com/46285015/163689251-4e851676-b49d-4e32-ae5b-826ee6f381f2.PNG)
.

**Comment by ITFixEZ** [comment]
clearedCache and allowed db to rebuild; it took about 3 days to complete download, but prior proper information is now displaying. I am going to keep locked until next compensation period is over and attempt a withdraw once again. TY issue resolved and closed !!
