### ISSUE TITLE
Start according to the prompt, but create a wallet with an error, and a screenshot of the error

### ISSUE THREAD

**Issue by zhb666** [nervosnetwork/neuron#2338]
![image](https://user-images.githubusercontent.com/18475950/164426464-ce4d92d9-305e-4e42-8e6c-5d9a3a5bbc92.png)
Import the wallet, create a new wallet and report an error

**Comment by Keith-CY** [comment]
Hi @zhb666, is this a screenshot of browser but not an electron's window?

If yes, this exception is reasonable since `ipcRenderer` is an object injected from electron's main process into electron's renderer process, which means `ipcRenderer.invoke` is available only in electron's window while `undefined.invoke` will be called in browsers.

This usually happens on running `npm run start` in `packages/neuron-ui` to start the UI independently. Please run `npm run start` in the root dir and an electron's window should prompt.

**Comment by zhb666** [comment]
Thanks for the reply, I switched to the root directory to start, I also started electron and mainWindow.loadURL("http://localhost:3000"); but this error is still reported

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/18475950/164441791-b4e7152d-78a3-4957-980c-bc267a1d2ec0.png">

**Comment by Keith-CY** [comment]
> Thanks for the reply, I switched to the root directory to start, I also started electron and mainWindow.loadURL("http://localhost:3000"); but this error is still reported
> 
> <img alt="image" width="1086" src="https://user-images.githubusercontent.com/18475950/164441791-b4e7152d-78a3-4957-980c-bc267a1d2ec0.png">

It's kind of weird.

This error indicates that `ipcRenderer` is not injected into the window, which should be caused by error on loading `preload.js`(https://github.com/nervosnetwork/neuron/blob/38b6afeb965d1befbb1437c9e2d1503099153e0c/packages/neuron-wallet/src/controllers/app/index.ts#L132)

Could you add some logs in https://github.com/nervosnetwork/neuron/blob/38b6afeb965d1befbb1437c9e2d1503099153e0c/packages/neuron-wallet/src/controllers/app/preload.ts to see if this file is executed on instantiating the main window?

**Comment by zhb666** [comment]
I found the problem. I opened an online version locally to download and install the neuron program, and then the program couldn't be opened after startup. I don't know why this problem would conflict. Just turn off the installed neuron
