### ISSUE TITLE
After Neuron update, isn't syncing at all. Also, check for updates doesn't do anything

### ISSUE THREAD

**Issue by EthAnalysis** [nervosnetwork/neuron#2370]
**Describe the bug** (Please enter details, the more detail the better)
Neuron was working fine on Windows11 64bit before the update. Now after the update, the notification at the bottom left doesn't move (neither the current block or synced block)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)
[neuron_debug_1651985131217.zip](https://github.com/nervosnetwork/neuron/files/8646354/neuron_debug_1651985131217.zip)

**Screenshots** (If applicable, add screenshots to help explain your problem.)
![image](https://user-images.githubusercontent.com/93758917/167282143-4638f739-5ae0-4b7b-82b1-e6c924c5da40.png)

**Comment by Keith-CY** [comment]
Hi @EthAnalysis , the last error message from the logs is
```
        const txHash = tx.hash;
                          ^
TypeError: Cannot read properties of null (reading 'hash')
```

Which is a known error leading to stop of synchronization and has been fixed in the next release(will be released on 05/10)

This error comes along with a rejected transaction. Since the tx has been rejected, Neuron cannot fetch it from the chain so the logic broke, `clear cache with rebuilding index` could fix it too by removing the rejected transaction from local cache.

**Comment by EthAnalysis** [comment]
Perfect @Keith-CY , the last bug fix update corrected it. All is syncing fine now!
