### ISSUE TITLE
Can't update to 0.103.0 on MacOS X64

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/neuron#2374]
**Describe the bug** (Please enter details, the more detail the better)

Click update in preference and pop this

<img width="413" alt="image" src="https://user-images.githubusercontent.com/15355789/167580801-de74cd11-0517-4d30-9b6e-5afa017b53e2.png">

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
Hi @timfaner 

You cannot upgrade Neuron from v0.101.2 and before to v0.103.0 because we've updated Neuron's Apple Developer Id Certificate in v0.101.3. When you upgrade Neuron from v0.101.2 to v0.103.0, the certification verification should fail.

You may download Neuron from the [release page](https://github.com/nervosnetwork/neuron/releases/tag/v0.103.0) to adopt the new certificate.

**Comment by timfaner** [comment]
Thx, I download manually and succeed
