### ISSUE TITLE
Neuron wallet not depositing to DAO / stuck in pending

### ISSUE THREAD

**Issue by ansidaze** [nervosnetwork/neuron#2382]
I'm having the same issue as some others here. I'm afraid to kill the wallet and re-launch since it's a sizable deposit at risk. 

![image](https://user-images.githubusercontent.com/77987648/168306489-ece153fd-861a-432e-a994-ecb436a8045d.png)

![image](https://user-images.githubusercontent.com/77987648/168306281-dcba03e9-5a93-411b-bab2-19d319987274.png)

I appreciate any help!

**Comment by Keith-CY** [comment]
Hi @ansidaze , we are still working to find out the problem, I can reproduce the pending deposit transactions with neuron@v0.101.3 and found those transactions are done in neuron@v0.103.0(I comment details in https://github.com/nervosnetwork/neuron/issues/2377#issuecomment-1126665948), please upgrade your neuron and have a look.

You can upgrade neuron from `menu -> help -> check for updates` since the same button in the setting window has a bug now.

**Comment by Keith-CY** [comment]
> Hi @ansidaze , we are still working to find out the problem, I can reproduce the pending deposit transactions with neuron@v0.101.3 and found those transactions are done in neuron@v0.103.0(I comment details in [#2377 (comment)](https://github.com/nervosnetwork/neuron/issues/2377#issuecomment-1126665948)), please upgrade your neuron and have a look.
> 
> You can upgrade neuron from `menu -> help -> check for updates` since the same button in the setting window has a bug now.

I've confirmed it, upgrade to neuron@v0.103.0 should fix it

Ref: https://github.com/nervosnetwork/neuron/issues/2384
