### ISSUE TITLE
I am trying to add a receiving address to crypto.com from the Neuron wallet that I connect to using ledger Nano X. When i get the receiving address from the Neuron wallet, and verify on ledger Nano X, they are different, so I have to reject the address and can't whitelist the address in crypto.com to send funds from there to my wallet. 

### ISSUE THREAD

**Issue by rob4949** [nervosnetwork/neuron#2391]
**Describe the bug** (Please enter details, the more detail the better)

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

**Comment by Keith-CY** [comment]
Hi @rob4949 

You may encounter a known issue about CKB Address format upgrade with the last harkfork on 05/20

Since hardfork, neuron starts to display addresses in the new format listed in the [address format rfc](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md) while other applications in CKB ecosystem need time to follow up.

Neuron has started a task to display addresses in the deprecated address format if user requires, can be tracked in this issue https://github.com/Magickbase/neuron-public-issues/issues/22

And there're two solutions to transform address between deprecated format and current format

1. visit the address page in explorer and you may find a link next to the address, it will link to the counterpart address
![image](https://user-images.githubusercontent.com/7271329/169521496-e580b2f9-ad06-48bf-8e6c-78d8a4e0d072.png)
2. we built a web tool to transform address into current format and deprecated format simultaneously. https://lumos-website.vercel.app/tools/address-conversion

**Comment by rob4949** [comment]
I checked your response and I understand the what you guys did. I also pasted my address from the Neuron wallet into the tool you built, and the short old code matched what I am seeing on my ledger nano X. However, I am not able to verify using ledger because I can't switch the address in the Neuron wallet to match my nano X. Are you going to have an update for the Neuron wallet in Ledger Manager soon, so that I can update my nano with this new information?
