### ISSUE TITLE
New address format: Not possible to send CKB from Binance to Neuron

### ISSUE THREAD

**Issue by panmoria** [nervosnetwork/neuron#2397]
Message from Binance:

"Hi, I received the update from the team, for the new format address at this moment, We're informed by tech previously this format might be supported in the near future. We will update once an ETA is available."

They ask to check with Neuron wallet, that Binance has not supported the new address, so is there any way to transfer the fund from Binance to Neuron wallet.

They say old addresses are working, but updated Neuron Wallet doesn't display old addresses.

Can formerly used old addresses still be used? Or how to transfer into Neuron?

**Comment by Keith-CY** [comment]
> Message from Binance:
> 
> "Hi, I received the update from the team, for the new format address at this moment, We're informed by tech previously this format might be supported in the near future. We will update once an ETA is available."
> 
> They ask to check with Neuron wallet, that Binance has not supported the new address, so is there any way to transfer the fund from Binance to Neuron wallet.
> 
> They say old addresses are working, but updated Neuron Wallet doesn't display old addresses.
> 
> Can formerly used old addresses still be used? Or how to transfer into Neuron?

Hi @panmoria 
Addresses used previously are still valid now, they are just displayed in different way but has the same identities.

And you can view the old address in transaction detail in Neuron by clicking the “secp256k1/blake160” tag next to your address, the deprecated address will appear as the screenshot in this PR
https://github.com/nervosnetwork/neuron/pull/2358

**Comment by panmoria** [comment]
“secp256k1/blake160” tag ...

Can you kindly provide a screenshot where to find this?

**Comment by Keith-CY** [comment]
https://user-images.githubusercontent.com/7271329/169933923-c72115e7-9855-4361-8b3d-6a160bbbc518.mov

Receiving address of test wallet is located by the amount. In this video, I received around 77 ckb, then the address received 77 ckb in output is mine.

The address in this video is `ckb1qyqrg2awc2chs9yj3l34x9pglsnnxtsvpv6s2d3gfx` in old format and `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf59whv9vtczjfglc6nzs50cfen9cxqkdg6vv8dq` in new format, you can visit ckb explorer and will find they have the same history.

**Comment by panmoria** [comment]
Thanks much, appreciate!

**Comment by Keith-CY** [comment]
> This seems a risky approach, I tried to check with several old RECEIVE transactions in Neuron, and they all show a wrong exchange address. Luckily did a test transaction with minimal loss. Guess the only way is to dig out old transactions!

Hi @panmoria 
Do you mean that you were trying to find out an old receive address from Neuron's history but got an exchange address?

I guess there're two addresses in outputs of one transaction, one is from Neuron and one is from the exchange. We have to distinguish them carefully(this step is risky because we have to do it manually).

As the video shows, I picked a transaction receiving 77 CKB, I **guess** the address receiving 77 CKB in the transaction is mine, then I visit the address book to verify it.

------

You can transform addresses between new/old formats with a new feature in CKB Explorer too.

Say the address I mentioned in the example is `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf59whv9vtczjfglc6nzs50cfen9cxqkdg6vv8dq`(new format), I can visit the explorer https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf59whv9vtczjfglc6nzs50cfen9cxqkdg6vv8dq and a link next to the address leads me to its old format 
![image](https://user-images.githubusercontent.com/7271329/169980840-e8b87a52-19f4-43c8-9ae1-5760dfe9a3bf.png)
https://explorer.nervos.org/address/ckb1qyqrg2awc2chs9yj3l34x9pglsnnxtsvpv6s2d3gfx

They have the same history, except in different address format

**Comment by Kempachi23** [comment]
i have tried transfer CKB from BINANCE to NEURON using old neuron wallet address and it was a failure, binance wont even transfer it..mybe the old address is unusable after the mainnet upgrade.. 

The real question is when will Binance will support the new wallet address??

**Comment by Kempachi23** [comment]
> This seems a risky approach, I tried to check with several old RECEIVE transactions in Neuron, and they all show a wrong exchange address. Luckily did a test transaction with minimal loss. Guess the only way is to dig out old transactions!

https://github.com/nervosnetwork/neuron/issues/2397#issuecomment-1140488641

**Comment by Keith-CY** [comment]
> i have tried transfer CKB from BINANCE to NEURON using old neuron wallet address and it was a failure, binance wont even transfer it..mybe the old address is unusable after the mainnet upgrade..
> 
> The real question is when will Binance will support the new wallet address??

@quake do you have any idea about the schedule for adopting the new address format in Binance?

**Comment by Kempachi23** [comment]
> > i have tried transfer CKB from BINANCE to NEURON using old neuron wallet address and it was a failure, binance wont even transfer it..mybe the old address is unusable after the mainnet upgrade..
> > 
> > The real question is when will Binance will support the new wallet address??
> 
> @quake do you have any idea about the schedule for adopting the new address format in Binance?

No idea bro as i already emailed them but still no response..

**Comment by Keith-CY** [comment]
Hi @panmoria @Kempachi23 
We just released https://github.com/nervosnetwork/neuron/releases/tag/v0.103.1 which could display receiving address in the deprecated format with PR https://github.com/nervosnetwork/neuron/pull/2408

https://user-images.githubusercontent.com/7271329/173193753-92518744-f9db-4506-9355-733d8b118681.mov
