### ISSUE TITLE
Generate Ledger wallet address from Neuron via the Ledger App is not valid

### ISSUE THREAD

**Issue by gillouche** [nervosnetwork/neuron#2431]
Hello,

**Describe the bug** (Please enter details, the more detail the better)
I have a Ledger Nano X, the Nervos app on the Ledger is 0.5.4 and Neuron Wallet 0.103.0. I imported a wallet from the Ledger Nano X.

In Neuron Wallet, when I click on receive and then "Verify Address" and confirm on the Ledger Nano X, the status is "Invalid". 

Because of that, I cannot send CKB on the Ledger via the Neuron Wallet.

Is it a problem with the Ledger, the Nervos Ledger App, or Neuron Wallet?

Thanks.

**Comment by Keith-CY** [comment]
Hi @gillouche 

Nervos Ledger App should be updated since hardfork happened on 05/10, by that short version address(Nervos Ledger App was using) has been deprecated and a new universal address is proposed(Neuron is using).

But Nervos Ledger App doesn't catch up with the new format AFAIK, and core team is pushing the adaption.

Address Format RFC: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md

**Comment by gillouche** [comment]
Hi @Keith-CY 
thanks, it is more clear now.

**Comment by Keith-CY** [comment]
Hi @gillouche 

Because the ETA. of updating ledger live app is not confirmed, we released neuron v0.103.2 https://github.com/nervosnetwork/neuron/releases/tag/v0.103.2 that regards the deprecated addresses as valid addresses for compatibility.

**Comment by gillouche** [comment]
Thanks for the quick update @Keith-CY. 

Unfortunately, I need the Ledger app to be updated because the exchange does not accept the long address as valid. I'll try to see with the app maintainer.

**Comment by Keith-CY** [comment]
> Thanks for the quick update @Keith-CY.
> 
> Unfortunately, I need the Ledger app to be updated because the exchange does not accept the long address as valid. I'll try to see with the app maintainer.

Hi @gillouche 

I missed a part of Neuron's work on compatibility

Ledger shows the deprecated short address when it's not upgraded and was marked unverified because Neuron only admits the new format one.

After some work, Neuron admits the deprecated address offered by ledger so `verify address` passes now.

Besides, Neuron added a toggle in https://github.com/nervosnetwork/neuron/pull/2408 so a receiving address in the deprecated format is accessible too.

Now if you want to transfer some CKB from an exchange to Neuron, you can visit the `Receive` tab, toggle the address into the deprecated format and verify it with ledger, the short address displayed in neuron should be the same as one in ledger and can be used in the exchange.

**Comment by gillouche** [comment]
Okay, thank you very much @Keith-CY, I'll try this with a test transfer today or tomorrow.

Cheers.
