### ISSUE TITLE
Path dialogs for "data" and "indexer" selection are inconsistent

### ISSUE THREAD

**Issue by matt-nervos** [nervosnetwork/neuron#2459]
When selecting alternative folders for "data" and "indexer" locations, it seems that the dialog is looking for different directories levels, which leads to some troubleshooting from the user.

Screenshots show configuration and actual folder paths
<img width="391" alt="2" src="https://user-images.githubusercontent.com/88007636/181836069-0e7ea852-089c-4971-9ad3-e05028e510b5.png">
<img width="667" alt="1" src="https://user-images.githubusercontent.com/88007636/181836070-d388d3a1-e48e-45b0-9b67-d5367bf20902.png">

The "data" and "indexer" directories are at the same folder level but are required to be differently specified in Neuron to reach the path.

It seems like the path is assuming (or creating) the "data" folder, but "indexer" folder is directly specified

**Comment by mattquinn-nervos** [comment]
this is a little tricky because if the user is copying the data, they already have a "data" folder, but if they are syncing for the first time the data folder has to be created.

Maybe some GUI message is best, not sure of exactly the justification for why things are this way

**Comment by Cedar67** [comment]
Hi @mattquinn-nervos ,
The two directories are independent and do not affect each other. So they need to be set separately.
About the Node Data directory, Neuron automatically recognizes if a CKB Node is available in that directory and starts it. If no CKB Node is available in the directory, Neuron automatically initializes a Mainnet CKB Node.
About the Indexer Data directory, Neuron also automatically recognizes if there are any old Indexer Data available in the directory. If no Indexer Data is available in the directory, Neuron automatically creates an Indexer directory based on the current CKB node.

**Comment by mattquinn-nervos** [comment]
Thanks @Cedar67 , I appreciate the explanation.

Can you understand why it is confusing to a user? When I directly select the "indexer" folder, things work ok, when I directly select the "data" folder, Neuron creates the node directories in that folder, instead of seeing that there is already node data in that folder. Hope my explanation makes sense

**Comment by Cedar67** [comment]
> Thanks @Cedar67 , I appreciate the explanation.
> 
> Can you understand why it is confusing to a user? When I directly select the "indexer" folder, things work ok, when I directly select the "data" folder, Neuron creates the node directories in that folder, instead of seeing that there is already node data in that folder. Hope my explanation makes sense

Thank you for your additional description. @mattquinn-nervos  
when we directly select the "data" folder, Neuron automatically detects whether a node is already available in the current specified directory. It don't always create Node directories. If you find any situation that does not conform to this logical flow, could you please provide reproduce information so that we can locate it?
In addition, the Node Data directory Settings, here is not only set the `Data` storage path, also includes the `Node configuration, log and other related files and folders`. It can be confusing to the user. Neuron plans to change the name of this label to[ "CKB Node Config & Storage"](https://github.com/Magickbase/neuron-public-issues/issues/49) in the next release.

**Comment by mattquinn-nervos** [comment]
Thanks for replying, it does look like this hits a bug somewhere in the code path.

I'm including screenshots of before and after updating configuration to point directly at the folder. A new "data" subdirectory is created, but block # still comes from parent "data" directory but the node won't sync. 

The new subdirectory is basically empty.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/88007636/182396516-5c8630f8-16b2-4b27-a682-544b0f42d741.png">

 change to 
 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/88007636/182396842-32dbf27f-da23-4eb7-8e0e-ab5361647394.png">

 
<img width="301" alt="image" src="https://user-images.githubusercontent.com/88007636/182396905-a040cfe5-f83e-4625-bc52-b959c0504e15.png">

**Comment by Cedar67** [comment]
> Thanks for your reply, it does look like this hits a bug somewhere in the code path.
> 
> I'm including screenshots of before and after updating configuration to point directly at the folder. A new "data" subdirectory is created, but block # still comes from parent "data" directory but the node won't sync.
> 
> After about 15 minutes, this is still the same <img alt="image" width="251" src="https://user-images.githubusercontent.com/88007636/182397749-ed04f9d7-5f81-45b5-8c1f-89d5614c76b5.png">

@mattquinn-nervos  Thank you for the issue of feedback.

The Neuron page shows the synch status and progress of the **`Indexer`**, not the CKB node. Since the CKB node path has a new empty directory, the CKB node data needs to be resynchronized from scratch. This process may take several hours.
[this issue](https://github.com/Magickbase/neuron-public-issues/issues/50) will optimize it to reduce user confusion.
If you want to restore synchronization as soon as possible, migrate all the contents of the previous CKB node directory to the new directory before setting a new directory.

**Comment by mattquinn-nervos** [comment]
thanks @Cedar67  . The sync doesn't start in this circumstance. 

I would expect when directly selecting the "data" directory Neuron would see there is node data in that folder, from your comment "when we directly select the "data" folder, Neuron automatically detects whether a node is already available in the current specified directory."

however Neuron does not detect that node data is there and creates a new "data" folder inside that folder and shows the current block height from the indexer and stalls

**Comment by Cedar67** [comment]
@mattquinn-nervos thanks for your reply.
> I would expect when directly selecting the "data" directory Neuron would see there is node data in that folder, from your comment "when we directly select the "data" folder, Neuron automatically detects whether a node is already available in the current specified directory."
> 
> however Neuron does not detect that node data is there and creates a new "data" folder inside that folder and shows the current block height from the indexer and sync is stalled

By detecting CKB node profiles(Shown below), Neuron determines whether valid node exist, not through the `Data` directory.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/64718893/183546736-c69d30cc-bef7-420e-9883-9cd32969f63c.png">


> The sync doesn't start from genesis in this circumstance, it stalls at the indexer block height, it seems like something is not matching up with expected behavior

This will be fixed. When CKB node data is resynchronized from scratch, Indexer data is also resynchronized from 0%.

**Comment by Keith-CY** [comment]
This issue may be stale later because `ckb indexer` is going to be integrated into `ckb node`.

Along with this update, there's only one path for data storage.

Ref: https://github.com/nervosnetwork/ckb/pull/3609
