### ISSUE TITLE
[Synchronization] Nervos Wallet Sync Doesn't Start

### ISSUE THREAD

**Issue by AloisLienTDF** [nervosnetwork/neuron#2466]
### Detail of the issue

Hi Team!

I can't sync my Nervos PC wallet (NB: with hardware Ledger key). I followed all the instructions that TG mod gave me (wallet update, another network added, cache/data cleared, etc.) but it didn't solve anything. 

Please see the Debug Information below.

All the best,
Aloïs

[bundled-ckb.log](https://github.com/nervosnetwork/neuron/files/9306857/bundled-ckb.log)
[main.log](https://github.com/nervosnetwork/neuron/files/9306859/main.log)

### status.log

```shell
{"neuron":{"version":"0.103.2","blockNumber":"0"},"ckb":{"url":"http://localhost:8114","version":"","blockNumber":"","peers":[]},"client":{"platform":"win32","arch":"x64","release":"10.0.19044","vcredist":true}}
```

**Comment by yanguoyu** [comment]
@AloisLienTDF
I'm so sorry for my late response.
Your upload `main.log` and `bundled-ckb.log` is empty, so we cannot find anything from them.
From your sign `Aloïs`, I guess maybe your problem is the same as https://github.com/nervosnetwork/neuron/issues/2497, If so you can refer to this [comment](https://github.com/nervosnetwork/neuron/issues/2497#issuecomment-1270288737).
And now `Neuron` has updated to 0.106, maybe you can download it and try it again.
