### ISSUE TITLE
withdraw from coinex to neuron

### ISSUE THREAD

**Issue by Nirach369** [nervosnetwork/neuron#2502]
I sent CKB to neuron but I didnt received.

https://explorer.nervos.org/transaction/0x5913161cd6540a87e3ff253a1cc529dadc022b3084bc29dd3e1ea13cb7719e7b

**Comment by yanguoyu** [comment]
`ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0g2tsu8c67vpcmqxxygd9qlyhg9gp4snslc5cx4` and `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfwk9e4967gj6327l4pa9zua7ecejc8zwc0q5ql2` has receive the CKB.
If `Neuron` doesn't display it, it maybe happened because of the:
1. Your `Neuron` didn't sync to 100%
2. Your `Neuron` wallet does not include this address.

**Comment by Nirach369** [comment]
> `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0g2tsu8c67vpcmqxxygd9qlyhg9gp4snslc5cx4` and `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfwk9e4967gj6327l4pa9zua7ecejc8zwc0q5ql2` has receive the CKB. If `Neuron` doesn't display it, it maybe happened because of the:
> 
> 1. Your `Neuron` didn't sync to 100%
> 2. Your `Neuron` wallet does not include this address.

Thanks for your response.
If I disconnect  from internet, will the sync continue?

**Comment by yanguoyu** [comment]
> 

Sync needs to connect internet. And you can also see the sync status on the left of `Neuron`.
