### ISSUE TITLE
Ledger device: UNKNOWN_ERROR (0x9405)

### ISSUE THREAD

**Issue by cjdj1513** [nervosnetwork/neuron#2578]
Im getting this error using my Ledger nano X when trying to withdraw after hitting the Proceed>sign button. It does this for about half of my deposits, the other half works. 

![image](https://user-images.githubusercontent.com/124013689/215648063-9c563fdb-5287-4b47-a11f-240ad51855e7.png)

**Comment by Keith-CY** [comment]
> Im getting this error using my Ledger nano X when trying to withdraw after hitting the Proceed>sign button. It does this for about half of my deposits, the other half works.
> 
> ![image](https://user-images.githubusercontent.com/124013689/215648063-9c563fdb-5287-4b47-a11f-240ad51855e7.png)

Hi @cjdj1513 
Could you provide the log of neuron which could be exported by `Menu => Help => Export debug information` so we can figure out what happened internally?

Besides, the version of Ledger CKB App would help us to reproduce this case.

**Comment by cjdj1513** [comment]
CKB Ledger App version 0.5.5

[neuron_debug_1675133553351.zip](https://github.com/nervosnetwork/neuron/files/10542236/neuron_debug_1675133553351.zip)

**Comment by Keith-CY** [comment]
> CKB Ledger App version 0.5.5
> 
> [neuron_debug_1675133553351.zip](https://github.com/nervosnetwork/neuron/files/10542236/neuron_debug_1675133553351.zip)

The unknown error was thrown from Ledger, so we cannot get detailed message.

But I noticed that you're using Ledger CKB App v0.5.5. It's the version that we just received a report of showing different address from that in Neuron(https://github.com/Magickbase/neuron-public-issues/issues/98)

May I ask if the addresses shown in Neuron and ledger are the same? If not, could you send the 2 addresses to `neuron@magickbase.com` then we can check which one is incorrect.

**Comment by cjdj1513** [comment]
Can you explain how to do this? Thank you

**Comment by Keith-CY** [comment]
> Can you explain how to do this? Thank you

1. Copy address shown in Neuron
![image](https://user-images.githubusercontent.com/7271329/215660288-fd70d5d3-56c9-4831-8ad6-42cbc3a9cd2d.png)
2. Take a photo of address shown in Ledger
3. Open an e-mail to Neuron Team
![image](https://user-images.githubusercontent.com/7271329/215660415-eb8ab960-d5cd-47d7-be32-fa075cd9755b.png)
4. Send the address and photo to neuron team e-mail

Then we can check if the 2 addresses are different.

**Comment by cjdj1513** [comment]
Doesn't make any sense, I withdraw from one of the deposits that allow me to withdraw then the deposits that would not allow me no will allow it. Thoughts?

**Comment by Keith-CY** [comment]
> Doesn't make any sense, I withdraw from one of the deposits that allow me to withdraw then the deposits that would not allow me now will allow it. Thoughts?

I cannot get the exact reason for this failure because the error message from Ledger is obscure.

Today we got another report(https://github.com/Magickbase/neuron-public-issues/issues/98) of inconsistent addresses shown in Neuron and Ledger, which happened on Neuron@v0.106 and Ledger X/S Plus with Ledger CKB App@v0.5.5. Then I think they may come from the same reason, and want to check if it happens on your device too.

If it happens, we can analyze the addresses on Ledger to figure out why the verification fails.

Otherwise, we'd better request help from Ledger Team to get the underlying error instead of `Unknown_error(0x9405)`.

I've found another case of `Unknown_error(0x9405)`, which is fixed by reinstalling the Ledger App. However, no official document was found about it.

Ref:
Fixed by reinstalling Ledger App: https://www.reddit.com/r/ledgerwallet/comments/rh4lc0/swap_failed_ledger_device_unknown_error_0x9405/

**Comment by Keith-CY** [comment]
Hi @cjdj1513 

We've confirmed that **Ledger X & Ledger CKB App 0.5.5** has a bug in generating the address, detailed info can be found in https://github.com/Magickbase/neuron-public-issues/issues/98#issuecomment-1412481315

The bug has been reported to ledger team, and **Ledger CKB App 0.5.0** works well

**Comment by cjdj1513** [comment]
Thank you ill try it.
