### ISSUE TITLE
messages.code.SQLITE_MISUSE after installation (arm64)

### ISSUE THREAD

**Issue by AlexanderFSP** [nervosnetwork/neuron#2612]
**Describe the bug** (Please enter details, the more detail the better)

messages.code.SQLITE_MISUSE after installation (arm64) and connecting hardware wallet. Also I tried to install sqlite by my own using homebrew, but it didn't help.

Neuron Version: 0.106.0
CKB Client Version: v0.106.0
OS: macOS Ventura, Apple M2 Max

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

Cannot attach it because:

<img width="1728" alt="Снимок экрана 2023-03-18 в 22 53 34" src="https://user-images.githubusercontent.com/30397060/226130252-688e4f8e-3379-4459-9a6f-71ff8156d059.png">

**Screenshots** (If applicable, add screenshots to help explain your problem.)

<img width="1728" alt="Снимок экрана 2023-03-18 в 22 51 32" src="https://user-images.githubusercontent.com/30397060/226130165-0784b5ca-9c2c-40b7-b724-55a1a91cb62d.png">

**Comment by Keith-CY** [comment]
Hi @AlexanderFSP 

Here's a similar issue(https://github.com/nervosnetwork/neuron/issues/2575) and a workaround(https://github.com/nervosnetwork/neuron/issues/2575#issuecomment-1406158751) for it

This problem was fixed by https://github.com/nervosnetwork/neuron/pull/2609 and will be delivered by the next version.

**Comment by AlexanderFSP** [comment]
@Keith-CY , ah, ok, thank u. So I'll close the current one.
