### ISSUE TITLE
unlocking CKB from the DAO is not responsive

### ISSUE THREAD

**Issue by Tung40194** [nervosnetwork/neuron#2937]
**Describe the bug** (Please enter details, the more detail the better)
- Mainnet light client is fully synced but can not unlock CKB I have withdrawn several days ago on another computer with Mainnet full client.

**Debug info** (Please upload the debug info from `Help` - `Export Debug Information`)

**Screenshots** (If applicable, add screenshots to help explain your problem.)

https://github.com/nervosnetwork/neuron/assets/70423834/79a551a4-c8a6-4764-b96b-7f2b0b2bb76c

**Comment by Keith-CY** [comment]
Hi @Tung40194 

We do find that **Unlocking Nervos DAO is broken on Light Client Mode** because of an upgrade of SDK, and we will fix it in the next release. Meanwhile, **Unlocking Nervos DAO** is still available on **Full Node Mode**

The fix can be tracked at https://github.com/Magickbase/neuron-public-issues/issues/316

The broken was introduced by SDK because it relies on an **experimental** API of CKB Full Node to estimate the total amount of a withdrawal. However, the API is marked as `experimental`(https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-calculate_dao_maximum_withdraw), and not available on CKB Light Client. Thus, the SDK doesn't work properly when it's connected to the Light Client.

The solution is simply moving the calculation of the total amount offline, so the experimental API won't be relied. We will deliver it ASAP.

**Comment by Tung40194** [comment]
thanks for the quick confirmation.

**Comment by Keith-CY** [comment]
Hi @Tung40194 
Neuron@v0.112.0 was just released at https://github.com/nervosnetwork/neuron/releases/tag/v0.112.0, and you can withdraw the deposit on light client mode now. Neuron can be upgraded by **Settings => General => Check for Updates**.

**Comment by Tung40194** [comment]
Thank you for your update!
