### ISSUE TITLE
NERVOS DAO UNLOCKED TOKEN PROBLEM

### ISSUE THREAD

**Issue by fab54800** [nervosnetwork/neuron#2943]
### Detail of the issue

HELLO … I can’t get my ckb back that has been stacked… In Nervos DAO a message is writting “CKB is ready to be unlocked” … and then i click on the green button " unlock " Nothing happens … MY ckb are always stacked … Do i have to wait several days? i dont get it !

on etherscan i have a message " unspent ckb " ..... can i send a image ?
please HELP ME
FABIAN

**Comment by Keith-CY** [comment]
Hi @fab54800 

We have found that **Unlocking Nervos DAO is broken on Light Client Mode** because of an upgrade of SDK, and we will fix it in the next release. Meanwhile, **Unlocking Nervos DAO** is still available on **Full Node Mode**

The fix can be tracked at https://github.com/Magickbase/neuron-public-issues/issues/316

The broken was introduced by SDK because it relies on an **experimental** API of CKB Full Node to estimate the total amount of a withdrawal. However, the API is marked as `experimental`(https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-calculate_dao_maximum_withdraw), and not available on CKB Light Client. Thus, the SDK doesn't work properly when it's connected to the Light Client.

The solution is simply moving the calculation of the total amount offline, so the experimental API won't be relied. We will deliver it ASAP.

**Comment by fab54800** [comment]
full node = INTERNAL NODE on the NEURON WALLET ?

**Comment by Keith-CY** [comment]
> full node = INTERNAL NODE on the NEURON WALLET ?

Yes, select the `internal node` switch into `full node mode`. On that mode, Neuron runs its internal CKB full node and sync the whore blockchain locally. The synchronization of full node takes time because there are 55 GB data to download.

**Comment by fab54800** [comment]
what is full node ? on NEURON WALLET there is "internal node" "light client" and "default node" ... which one to choose ??

**Comment by Keith-CY** [comment]
> what is full node ? on NEURON WALLET there is "internal node" "light client" and "default node" ... which one to choose ??

Oh I found you mentioned `default node`, it's a legacy option. Please check https://github.com/Magickbase/neuron-public-issues/issues/320 to make sure `internal node` works

**Comment by fab54800** [comment]
my NEURON WALLET is now synced 100% with the blockchain " internal node" and all is ok ... **thank you very much**  and good luck in your business .... NERVOS NETWORK TO THE MOON
