### ISSUE TITLE
[Bug Report] setting light client sync start block height greater than actual max block results in stuck condition

### ISSUE THREAD

**Issue by matt-nervos** [nervosnetwork/neuron#3006]
### Topic Type

User Experience

### Detail of the issue

When setting the start block height higher than actual block height, user cannot change the start block height 

<img width="303" alt="image" src="https://github.com/nervosnetwork/neuron/assets/88007636/aff0ed08-4126-42a2-b147-95bdec6db3be">
<img width="521" alt="image" src="https://github.com/nervosnetwork/neuron/assets/88007636/30cde49e-780d-495b-8f8d-c92343c21d7d">
<img width="691" alt="image" src="https://github.com/nervosnetwork/neuron/assets/88007636/f7466f1e-ea29-43a0-8eb1-4aba4803d2f4">
<img width="290" alt="image" src="https://github.com/nervosnetwork/neuron/assets/88007636/36eaaefc-3e3c-4fb4-a04a-6e2f13414141">

**Comment by Keith-CY** [comment]
Hi @matt-nervos I've found 2 cases in this issue
1. `start block number` was set higher than the tip block number;
2. `start block number` cannot be updated in some cases;

They are expected to be fixed in https://github.com/nervosnetwork/neuron/pull/2994

Setting the start block number greater than the tip one won't be allowed, and setting the start block number less than the current one is allowed, but a re-sync is mandatory.
