### ISSUE TITLE
Unable to unlock DAO assets

### ISSUE THREAD

**Issue by Ozimok11** [nervosnetwork/neuron#3090]
Hello!

The DAO withdrawal keeps hanging and just says "confirming" and spins with an orange arrow...for 12 days.  Then I reset cache and it was as if I never asked it to unlock and then did it again and its been hung for another 5 days.  Thoughts?  Thanks!

**Comment by yanguoyu** [comment]
Hi, @Ozimok11 
The DAO deposit needs two steps to withdraw it. For the phase 1 withdrawal, you can start at any time. For phase 2, we must wait for 180 epochs(about 30 days) at longest.
The detailed docs can be found here.https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#withdraw

The deposit DAO's stages passed can be viewed by hovering over the `deposit time label`
<img width="980" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/63cbd62d-9ff8-4a04-9c91-fe0655d08e36">

The records can be found in the `completed` tab if the deposit DAO has been unlocked.
<img width="985" alt="image" src="https://github.com/nervosnetwork/neuron/assets/12881040/da7a51f5-25bf-4c10-8572-68f4a17e4ccc">

You will get a transaction hash after you withdraw or unlock the deposit DAO. If the transaction broadcast success, it can be found at the [explorer](https://explorer.nervos.org/). And after the neuron synced the transaction, the transaction status will change. If the Neuron sync is stuck,  the information of the native wallet would help us check what happened, it can be exported by Menu => Help => Export debug information.

**Comment by Ozimok11** [comment]
[
[neuron_debug_1711026711531.zip](https://github.com/nervosnetwork/neuron/files/14695618/neuron_debug_1711026711531.zip)
](url)

**Comment by Ozimok11** [comment]
After I just resynced it still just shows teh 8 DAO deposits and has a green withdraw button now.  Nothing is showing pending.  Thanks!

**Comment by yanguoyu** [comment]
> After I just resynced it still just shows teh 8 DAO deposits and has a green withdraw button now. Nothing is showing pending. Thanks!

Hi, from the log, I get that your `Neuron` currently syncs to the `7150910` block, but now the highest block number is `12,517,172`. It's better to withdraw and unlock your deposit after the `Neuron` syncs to 100%. Your withdrawal transaction will broadcast to a higher block than the latest block number, so Neuron's withdrawal transaction status will not change until the Neuron syncs to the latest block number.

Additionally, the latest Neuron includes a light client node. The light client node will sync faster than the full node and needs less disk space because it only subscribes to your address. It can set the start block number to speed up the sync process.
The start block number should be set to lower than the first block number of your wallet.
If you want to use the light client click `setting` and scroll to the Network setting, then choose Light Client, which will switch to the Light Client.
![image](https://github.com/nervosnetwork/neuron/assets/12881040/3d85d145-9907-4289-a34c-b1c3ff01b944)

**Comment by Ozimok11** [comment]
It has an update available but it won't load...it has this error:

![image](https://github.com/nervosnetwork/neuron/assets/164344062/508e4b5c-8471-4e4d-a54b-7e719d6feae5)

I'm thinking fixing that and updating will fix my problem.

**Comment by Ozimok11** [comment]
Any ideas how to fix that error?  Thanks!

**Comment by yanguoyu** [comment]
> It has an update available but it won't load...it has this error:
> 
> ![image](https://private-user-images.githubusercontent.com/164344062/316095244-508e4b5c-8471-4e4d-a54b-7e719d6feae5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDk1MjMsIm5iZiI6MTcxMTE0OTIyMywicGF0aCI6Ii8xNjQzNDQwNjIvMzE2MDk1MjQ0LTUwOGU0YjVjLTg0NzEtNGU0ZC1hNTRiLTdlNzE5ZDZmZWFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQyMzEzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQ2NzY2OTdhZWYwNDlkMzRmMDY2ODdlZjk1NzE4YWEzMjY0ZTM4ODhiOWEzNjU1YzRjMGJkMWJkZDgxYzgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5RBDYgG0G0Y5zhlhNHQTQj-L9wse3RlsVfUcPFnkBZ0)
> 
> I'm thinking fixing that and updating will fix my problem.

Hi, we have updated the certificate, so Neuron cannot upgrade from v0.101.1 to the latest. But you can download Neuron from the [release page](https://github.com/nervosnetwork/neuron/releases/tag/v0.114.2) to adopt the new certificate, it should pass through the GateKeeper of macOS.
Refer to : https://github.com/nervosnetwork/neuron/issues/2386 https://github.com/nervosnetwork/neuron/issues/2314#issuecomment-1080256193

**Comment by Ozimok11** [comment]
It worked...thank you!
