### ISSUE TITLE
[Feature Request] Set proxy for internal full node or light client.

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/neuron#3099]
Due to the poor Internet in some countries, both the internal full node and the internal light client are really slow with the default configuration.

So, I used the parameter `--proxy-server="socks5://localhost:8888"` to start Neuron.
It's a common parameter for all Applications based on Electron.

But I found it didn't work for the internal node or the internal light client, it only worked for the Neuron itself. Because I only found logs to query `github.com` and `githubassets.com` from my proxy server.

As the developers of Neuron said in #3098:
> Self-hosted Light client is not allowed to be connected to Neuron

I think an official setting for set proxy for the internal node and the internal light client is required.

**Comment by Keith-CY** [comment]
Good point, it should be enabled in the following releases

**Comment by Keith-CY** [comment]
WIP

**Comment by Danie0918** [comment]
Sorry, we can't support this suggestion at this time. @yangby-cryptape 

After our technical team tried to develop it, we realized that node support was needed, but after evaluation by the ckb core team, it was not considered a high-priority task.

So we suggest you try global proxy or adjust proxy rules to add node proxy, because if only Neuron uses proxy can't control the node.

**Comment by Keith-CY** [comment]
Hi @yangby-cryptape 
Neuron@v0.117.0(https://github.com/nervosnetwork/neuron/releases/tag/v0.117.0) has supported external light clients, please have a try.
