### ISSUE TITLE
Unable to open Json file in Neuron 0.114.2

### ISSUE THREAD

**Issue by cashngrab** [nervosnetwork/neuron#3107]
### Topic Type

User Experience

### Detail of the issue

Hi!
I save my CKB Nervos file in Json format on my computer offline. I stake my CKB in DAO Neuron with Ledger Nano X. Now I'm trying to import Json file but its says "Invalid JSON file, please check your file integrity". Last time I was login December 2021.
Even when I connect my Ledger Nano X only it doesn't show my CKB coins. Nor its importing Json file. 

Any help will be greatly appreciated. Its so frustrating investing for so long and can't access my coins.

Thanks

**Comment by cashngrab** [comment]
Even if I tried to export extended public key on my current Neuron and try to import it right away its says the same phrase, "Invalid JSON file, please check your file integrity"

Is there any other supported CKB wallet where I can import my Json key while its staking in Neuron Dao? Will it fetch my coin back.

Please help.

**Comment by Keith-CY** [comment]
> Even if I tried to export extended public key on my current Neuron and try to import it right away its says the same phrase, "Invalid JSON file, please check your file integrity"
> 
> Is there any other supported CKB wallet where I can import my Json key while its staking in Neuron Dao? Will it fetch my coin back.
> 
> Please help.

Hi @cashngrab

This message is misleading because it's actually triggered by importing a watch wallet repeatedly. The message will be fixed later.

---

Speaking of that tokens are not displayed as expected, it's probably a synchronization problem. Neuron is a full node wallet, and it downloads data block by block, and finally display your assets when it downloads the latest block(12,678,046 at this moment). The synchronization progress is placed at the top right corner as this

<img width="420" alt="image" src="https://github.com/nervosnetwork/neuron/assets/7271329/9fb1470f-9db1-4960-9265-c6d1a131756f">

Please check if it's growing.

If yes, be patient for it to be 100%.

If not, the synchronization is halted and should be fixed, the **debug information** would help us to fix it. The **debug information** could be exported as a zip file by **Menu => Help => Export debug information** and can be uploaded by drag&drop it into the text box.

You can also send the debug information to neuron@magickbase.com if you don't want it to be exposed here, and we can continue this topic via email.
