### ISSUE TITLE
Is there a plan to support transferring to .bit accounts?

### ISSUE THREAD

**Issue by sunchengzhu** [nervosnetwork/neuron#3188]
I noticed that imToken and JoyID both support address resolution for .bit accounts. Does Neuron have any plans to support .bit accounts?

<img src="https://github.com/nervosnetwork/neuron/assets/36075573/1d5ee694-9991-44c5-90a8-09b90f0bee56" width="50%">

<img src="https://github.com/nervosnetwork/neuron/assets/36075573/f767eeec-50e2-4475-abea-8c38b7c21ca4" width="50%">

![image](https://github.com/nervosnetwork/neuron/assets/36075573/9ac81722-4bfc-4a50-9a97-1687bc22115b)

**Comment by Keith-CY** [comment]
Hi @sunchengzhu 
Sorry for replying late.

`.bit name resolution` won't be integrated shortly because the resolution service(generally called DNS) relies on an external service, which is not preferred for Neuron.

Neuron is a full-node wallet and gets data only from the node. Response from external services could be considered untrustworthy.
